/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface FabMenu {
      'fixed': boolean;
      'open': boolean;
    }
  }

  interface HTMLFabMenuElement extends StencilComponents.FabMenu, HTMLStencilElement {}

  var HTMLFabMenuElement: {
    prototype: HTMLFabMenuElement;
    new (): HTMLFabMenuElement;
  };
  interface HTMLElementTagNameMap {
    'fab-menu': HTMLFabMenuElement;
  }
  interface ElementTagNameMap {
    'fab-menu': HTMLFabMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'fab-menu': JSXElements.FabMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface FabMenuAttributes extends HTMLAttributes {
      'fixed'?: boolean;
      'open'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;